### ISSUE TITLE
Error processing a dataset that works with NodeODM

### ISSUE THREAD

**Issue by petergerten** [dronemapper-io/NodeMICMAC#14]
Hi,
thanks for you work - this looks very interesting.
I ran into the following issue:
```
------------------------------------------------------------
-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 207
|          of file : /var/www/micmac/src/uti_phgrm/Apero/GraphePose.cpp
-------------------------------------------------------------
Bye  (press enter)

```
I used the docker container. The imageset I used works find with NodeODM.
This might not be helpful - any suggestions on how get more information what went wrong here?

**Comment by pierotofy** [comment]
Hey @petergerten, would you be available to share your dataset? It would help a lot to troubleshoot the problem.

**Comment by smathermather** [comment]
Yes, I think we are going to see a bit of this until we have tuned NodeMICMAC and find the range of use cases and necessary settings. Datasets will help this process a lot.

**Comment by petergerten** [comment]
Unfortunately I can't share that particular dataset. I will check if I can reproduce the issue with a different dataset that I can share.

**Comment by kikislater** [comment]
Could you describe your data ? 
- Overlap / Sidelap
- Camera model
- Angle of camera 
- Subject : forest, urban, crop ...

**Comment by smathermather** [comment]
Also @petergerten, if you can share privately (sharing doesn't require that you post it for the world), that could help. But short of that, @kikislater's list above would help.

**Comment by dronemapper-io** [comment]
Hi,
You can try setting the "--resize-to" option to a higher value such as 1600 pixels. Default is 800.. that might help extract more tie-points. Or you could try the "--multi-scale" option which will attempt to extract tie-points and combine them from two different image resolutions. 

It is hard to know the exact issue without the full log output. Thanks, JP

**Comment by petergerten** [comment]
@dronemapper-io thanks - setting the resize-to value to 1600 made it work.
Will check further and provide more details on the failed run.

**Comment by dronemapper-io** [comment]
Good to hear that! Sounds like the images may be very homogeneous or difficult terrain to extract tie-points.. multi-scale or larger resize-to can definitely help
