### ISSUE TITLE
NodeMicMac terminates with Error in /var/www/micmac/src/util/stringifie.cpp line 417

### ISSUE THREAD

**Issue by rkuerbitz** [dronemapper-io/NodeMICMAC#27]
Dear team, I am trying to get NodeMICMAC to run with my DJI Mavic Pro images. I tried several datasets (48 images), and always get the following error message in the console output at 72% progress:

**(Elise's) LOCATION :
Error was detected
 at line : 417
 of file : /var/www/micmac/src/util/stringifie.cpp
Bye (press enter)**

I am running the NodeMICMAC docker image from docker hub on Windows Server 2019 with LCOW.
Any suggestions that might help?

**Comment by pierotofy** [comment]
Hey @rkuerbitz :hand: could you attach a copy of your dataset somewhere like google drive or dropbox? That would help a lot.

**Comment by rkuerbitz** [comment]
Hey pierotofy, I sent you a PM with a download link. Thanks for looking into this!

**Comment by pierotofy** [comment]
Shared with JP. Thanks.

**Comment by dronemapper-io** [comment]
The dataset processed for me .. maybe something related to file paths / docker under Windows

**Comment by kikislater** [comment]
> The dataset processed for me .. maybe something related to file paths / docker under Windows

Or not enough space available.

**Comment by rkuerbitz** [comment]
Dear JP and kikislater, thanks very much for looking into this and giving me feedback. I will consider/try to use another VM/docker setup.

**Comment by dronemapper-io** [comment]
closing for now, please follow up if still an issue.
