### ISSUE TITLE
ERROR: unauthorized: authentication required

### ISSUE THREAD

**Issue by mj-saunders** [dronemapper-io/NodeMICMAC#33]
when using `./webodm.sh restart --with-micmac`, dronemapper/node-micmac begins to be pulled, but as download "8de92fc01e3d" begins (not sure what pasrt of the package this actually refers to), I receive the titled error.

Not sure how to get around this.
Seems to be an issue with docker login ?

**Comment by mj-saunders** [comment]
appears to be an issue with the shell script.
I can't figure it out at the moment.

However, everything went smoothly when installing using `docker build -t dronemapper/node-micmac .
`
Just followed the first part of this (Getting Started) : https://github.com/dronemapper-io/NodeMICMAC.

And now webodm behaves nicely as it can find NodeMICMAC and not have to deal with installing it itself.

**Comment by dronemapper-io** [comment]
Thanks for the update. Are there any other details you can provide? Sounds like there might be a glitch in the webodm.sh script when pulling the NodeMM docker image.

**Comment by mj-saunders** [comment]
Not sure what more details I can get.
I can try to uninstall micmac and retry using webodm.sh to see if I see anything relevant.
Using: `5.2.6-arch1-1-ARCH`

Incidentally, I am not getting point clouds when using micmac currently.
Processes without error, then says "Point cloud tiles will not be generated: - opening in 3d view states "Could not load point cloud. This task doesn't seem to have one."
Though it will let me download Point Cloud PLY asset.
However, I currently have no other viewer for .ply files. I'll see what I can find.

Before I make that into a new thread, I'm running on the belief it may be related to the installation, which may of course be nonsense....

**Comment by mj-saunders** [comment]
@dronemapper-io
So, it was a time issue - somewhat like here: https://github.com/moby/moby/issues/2645

My hw clock and system time were out by only a few minutes.
Everything works fine after syncing.

Not sure why it worked when using the previously mentioned "manual" command...
