### ISSUE TITLE
Ran out of storage space

### ISSUE THREAD

**Issue by kylenessen** [dronemapper-io/NodeMICMAC#38]
I'm trying to process a linear mission with 722 jpg images, totaling around 5.84 GB. I've let it run without apparent issue for about 148 hours now, and upon checking the Diagnostic page in WebODM, I found that I have used all 173 GB allocated to the docker container. I have no other projects, either in progress or completed, loaded in the container. Returning to the Dashboard, the duration timer has reverted to 87 hours and the Task Output is now blank, leading me to believe the processing failed. 

As reference, here are my processing options:
` ccd-width: 13.2, max-concurrency: 8, multi-scale: true, resize-to: 2048, ccd-height: 8.8`

Is this a bug? Or do I need to allocate a lot more space to WebODM? 

Thanks!

**Comment by dronemapper-io** [comment]
You shouldn't have to allocate more space. Try running the job with
multi-scale enabled and the resize to 500 pixel. Unless it is a very
homogeneous scene, there is not a need to compute tie-points at 2048 pixel.
Also, if you just need a good ortho, set the zoom at 4. Tha should speed up
processing. Thanks

**Comment by kylenessen** [comment]
Great, thanks for the feedback. 

I was running out of space with nodeODM as well, which makes me think it was some other issue. I have resized my docker disk image, freed up some space on my drive, and will reprocess it based on your recommendations. 

Does resizing affect the quality of the ortho? Or is it just for tie-points? 

Thanks!

**Comment by dronemapper-io** [comment]
Yes, it only affects the initial tie-point creation and feature matching.
It does really impact the time and size of files created during the first
stage of processing (tie-points/features)
Thanks
